import { createContext, useContext } from 'react';

export const colors = {
  light: {
    background: '#f6f9fd',
    card: '#ffffff',
    text: '#1e2d45',
    textSecondary: '#7a8fa8',
    border: '#e0eaf7',
    primary: '#5b8fcf',
    primaryLight: '#d6e4f7',
    primarySoft: '#edf4fd',
    inputBg: '#f6f9fd',
    inputBorder: '#e0eaf7',
    navBg: '#f6f9fd',
    navBorder: '#e0eaf7',
    placeholder: '#7a8fa8',
    danger: '#e05c5c',
    dangerLight: '#fdeaea',
    success: '#5caa8a',
    successLight: '#e6f7f1',
    warning: '#e8832a',
    warningLight: '#fdf0e6',
    teal: '#a8d5cc',
    tealLight: '#e0f4f0',
    cardStat1: '#edf4fd',
    cardStat2: '#e6f7f1',
    cardStat3: '#fdf0e6',
    cardStat4: '#e0f4f0',
    // Sections crèche
    petiteSection: '#e0f4f0',
    petiteSectionText: '#5a9e94',
    grandeSection: '#fdf0e6',
    grandeSectionText: '#e8832a',
  },
  dark: {
    background: '#0d1520',
    card: '#1a2535',
    text: '#e8f0fb',
    textSecondary: '#7a8fa8',
    border: '#243047',
    primary: '#5b8fcf',
    primaryLight: '#1a2d4a',
    primarySoft: '#162238',
    inputBg: '#1a2535',
    inputBorder: '#243047',
    navBg: '#111d2e',
    navBorder: '#243047',
    placeholder: '#4a6080',
    danger: '#e05c5c',
    dangerLight: '#3a1a1a',
    success: '#5caa8a',
    successLight: '#1a3028',
    warning: '#e8832a',
    warningLight: '#3a2210',
    teal: '#a8d5cc',
    tealLight: '#1a2e2c',
    cardStat1: '#162238',
    cardStat2: '#1a3028',
    cardStat3: '#3a2210',
    cardStat4: '#1a2e2c',
    petiteSection: '#1a2e2c',
    petiteSectionText: '#a8d5cc',
    grandeSection: '#3a2210',
    grandeSectionText: '#e8832a',
  }
};

export const translations = {
  fr: {
    home: 'Accueil',
    children: 'Enfants',
    photos: 'Photos',
    messages: 'Messages',
    agenda: 'Agenda',
    settings: 'Réglages',
    myChildren: 'Mes enfants',
    welcomeBack: 'Bonjour',
    loginSubtitle: 'Connectez-vous à votre compte',
    email: 'Email',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié ?',
    login: 'Se connecter',
    noAccount: 'Pas encore de compte ?',
    createOne: 'Créer un compte',
    createAccount: 'Créer un compte',
    joinApp: 'Rejoignez Baby-link',
    firstName: 'Prénom',
    lastName: 'Nom',
    welcomeTo: 'Bienvenue sur\nBaby-link',
    onboardingSubtitle: 'Commencez par créer ou rejoindre une crèche',
    createNursery: 'Créer une crèche',
    joinNursery: 'Rejoindre une crèche',
    createNurseryTitle: 'Créer une crèche',
    createNurserySubtitle: 'Vous serez la directrice de cette crèche',
    nurseryName: 'Nom de la crèche',
    nurseryNamePlaceholder: 'Ex: Les Petits Anges',
    address: 'Adresse',
    addressPlaceholder: 'Adresse de la crèche',
    create: 'Créer la crèche',
    joinNurseryTitle: 'Rejoindre une crèche',
    joinNurserySubtitle: 'Entrez le code fourni par la directrice',
    invitationCode: "Code d'invitation",
    join: 'Rejoindre',
    director: 'Directrice',
    nurseryWorker: 'Puéricultrice',
    reportsToWrite: 'Rapports à rédiger',
    seeAll: 'Tout voir →',
    reportCalendar: 'Calendrier des rapports',
    allReports: 'Tous les rapports écrits',
    partialReports: 'Rapports partiels',
    noChildren: 'Aucun enfant pour le moment',
    addChild: '+ Ajouter',
    addChildTitle: 'Ajouter un enfant',
    childCode: 'Code enfant',
    dailyReport: 'Rapport du jour',
    lunchMeal: '🍽️ Repas midi',
    afternoonMeal: '🍎 Repas goûter',
    nap: '😴 Sieste',
    mood: '😊 Humeur',
    healthNotes: '🏥 Notes santé',
    generalNotes: '📝 Notes générales',
    privateJournal: '📓 Journal privé',
    privateJournalNote: 'Visible uniquement par les puéricultrices',
    saveDraft: '💾 Enregistrer brouillon',
    publishReport: '✓ Publier le rapport',
    draftSaved: 'Brouillon enregistré',
    reportPublished: 'Rapport publié !',
    draftNotVisible: "Non visible par les parents pour l'instant.",
    parentsCanSee: 'Les parents peuvent maintenant le consulter.',
    noMessages: 'Aucun message',
    writeReply: 'Écrire une réponse...',
    menuOfDay: '🍽️ Menu du jour',
    addMenu: 'Appuyez pour ajouter le menu du jour',
    saveMenu: 'Sauvegarder',
    menuSaved: 'Menu sauvegardé !',
    settingsTitle: 'Réglages',
    invitationCodes: "🔑 Codes d'invitation",
    staffCode: 'Code personnel (puéricultrices)',
    parentCode: 'Code parents',
    renewCodes: '🔄 Renouveler les codes',
    manageMembers: '👥 Gérer les membres',
    lightMode: '☀️ Passer en mode clair',
    darkMode: '🌙 Passer en mode sombre',
    deleteAccount: 'Supprimer le compte',
    logout: '→ Déconnexion',
    language: '🌍 Langue',
    noChildLinked: 'Aucun enfant lié',
    addChildWithCode: 'Ajoutez vos enfants avec le code fourni par la crèche',
    addChildArrow: 'Ajouter un enfant →',
    sendMessage: 'Envoyer un message',
    sendMessageSubtitle: "Prévenez l'équipe d'une info importante",
    todayReport: "📋 Rapport d'aujourd'hui",
    noReportToday: "Pas encore de rapport aujourd'hui",
    history: '📚 Historique',
    photosTitle: 'Photos',
    addPhoto: '+ Photo',
    takePhoto: '📷 Prendre une photo',
    choosePhoto: '🖼️ Choisir dans la galerie',
    setAvatar: 'Avatar',
    noPhotos: 'Aucune photo',
    membersTitle: 'Membres',
    parent: 'Parent',
    cancel: 'Annuler',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    error: 'Erreur',
    success: 'Succès',
    loading: 'Chargement...',
    back: '← Retour',
    add: 'Ajouter',
    save: 'Sauvegarder',
    send: 'Envoyer',
    present: 'Présent',
    absent: 'Absent',
    petiteSection: 'Petite section',
    grandeSection: 'Grande section',
    searchChild: 'Rechercher un enfant...',
    addMeal: '+ Ajouter un repas',
    addNap: '+ Ajouter une sieste',
    babyReport: 'Rapport bébé',
    bigReport: 'Rapport grands',
    bottle: 'Biberon',
    puree: 'Purée',
    compote: 'Compote',
    snack: 'Goûter',
    quantity: 'Quantité (ml)',
    time: 'Heure',
    duration: 'Durée (min)',
    startTime: 'Début',
    endTime: 'Fin',
  },
  en: {
    home: 'Home',
    children: 'Children',
    photos: 'Photos',
    messages: 'Messages',
    agenda: 'Agenda',
    settings: 'Settings',
    myChildren: 'My children',
    welcomeBack: 'Hello',
    loginSubtitle: 'Log in to your account',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    login: 'Log in',
    noAccount: "Don't have an account?",
    createOne: 'Create one',
    createAccount: 'Create account',
    joinApp: 'Join Baby-link',
    firstName: 'First name',
    lastName: 'Last name',
    welcomeTo: 'Welcome to\nBaby-link',
    onboardingSubtitle: 'Start by creating or joining a nursery',
    createNursery: 'Create a nursery',
    joinNursery: 'Join a nursery',
    createNurseryTitle: 'Create a nursery',
    createNurserySubtitle: 'You will be the director of this nursery',
    nurseryName: 'Nursery name',
    nurseryNamePlaceholder: 'Ex: The Little Angels',
    address: 'Address',
    addressPlaceholder: 'Nursery address',
    create: 'Create nursery',
    joinNurseryTitle: 'Join a nursery',
    joinNurserySubtitle: 'Enter the code provided by the director',
    invitationCode: 'Invitation code',
    join: 'Join',
    director: 'Director',
    nurseryWorker: 'Nursery worker',
    reportsToWrite: 'Reports to write',
    seeAll: 'See all →',
    reportCalendar: 'Report calendar',
    allReports: 'All reports written',
    partialReports: 'Partial reports',
    noChildren: 'No children yet',
    addChild: '+ Add',
    addChildTitle: 'Add a child',
    childCode: 'Child code',
    dailyReport: 'Daily report',
    lunchMeal: '🍽️ Lunch',
    afternoonMeal: '🍎 Afternoon snack',
    nap: '😴 Nap',
    mood: '😊 Mood',
    healthNotes: '🏥 Health notes',
    generalNotes: '📝 General notes',
    privateJournal: '📓 Private journal',
    privateJournalNote: 'Only visible to nursery workers',
    saveDraft: '💾 Save draft',
    publishReport: '✓ Publish report',
    draftSaved: 'Draft saved',
    reportPublished: 'Report published!',
    draftNotVisible: 'Not visible to parents yet.',
    parentsCanSee: 'Parents can now view it.',
    noMessages: 'No messages',
    writeReply: 'Write a reply...',
    menuOfDay: '🍽️ Menu of the day',
    addMenu: "Tap to add today's menu",
    saveMenu: 'Save',
    menuSaved: 'Menu saved!',
    settingsTitle: 'Settings',
    invitationCodes: '🔑 Invitation codes',
    staffCode: 'Staff code (nursery workers)',
    parentCode: 'Parent code',
    renewCodes: '🔄 Renew codes',
    manageMembers: '👥 Manage members',
    lightMode: '☀️ Switch to light mode',
    darkMode: '🌙 Switch to dark mode',
    deleteAccount: 'Delete account',
    logout: '→ Log out',
    language: '🌍 Language',
    noChildLinked: 'No child linked',
    addChildWithCode: 'Add your children with the code provided by the nursery',
    addChildArrow: 'Add a child →',
    sendMessage: 'Send a message',
    sendMessageSubtitle: 'Notify the team of important information',
    todayReport: "📋 Today's report",
    noReportToday: 'No report yet today',
    history: '📚 History',
    photosTitle: 'Photos',
    addPhoto: '+ Photo',
    takePhoto: '📷 Take a photo',
    choosePhoto: '🖼️ Choose from gallery',
    setAvatar: 'Avatar',
    noPhotos: 'No photos',
    membersTitle: 'Members',
    parent: 'Parent',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    error: 'Error',
    success: 'Success',
    loading: 'Loading...',
    back: '← Back',
    add: 'Add',
    save: 'Save',
    send: 'Send',
    present: 'Present',
    absent: 'Absent',
    petiteSection: 'Baby section',
    grandeSection: 'Toddler section',
    searchChild: 'Search a child...',
    addMeal: '+ Add a meal',
    addNap: '+ Add a nap',
    babyReport: 'Baby report',
    bigReport: 'Toddler report',
    bottle: 'Bottle',
    puree: 'Purée',
    compote: 'Compote',
    snack: 'Snack',
    quantity: 'Quantity (ml)',
    time: 'Time',
    duration: 'Duration (min)',
    startTime: 'Start',
    endTime: 'End',
  },
  nl: {
    home: 'Thuis',
    children: 'Kinderen',
    photos: "Foto's",
    messages: 'Berichten',
    agenda: 'Agenda',
    settings: 'Instellingen',
    myChildren: 'Mijn kinderen',
    welcomeBack: 'Hallo',
    loginSubtitle: 'Log in op uw account',
    email: 'E-mail',
    password: 'Wachtwoord',
    forgotPassword: 'Wachtwoord vergeten?',
    login: 'Inloggen',
    noAccount: 'Nog geen account?',
    createOne: 'Maak er een',
    createAccount: 'Account aanmaken',
    joinApp: 'Word lid van Baby-link',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    welcomeTo: 'Welkom bij\nBaby-link',
    onboardingSubtitle: 'Begin met het aanmaken of aansluiten bij een kinderdagverblijf',
    createNursery: 'Kinderdagverblijf aanmaken',
    joinNursery: 'Kinderdagverblijf aansluiten',
    createNurseryTitle: 'Kinderdagverblijf aanmaken',
    createNurserySubtitle: 'U wordt de directrice van dit kinderdagverblijf',
    nurseryName: 'Naam kinderdagverblijf',
    nurseryNamePlaceholder: 'Bijv: De Kleine Engeltjes',
    address: 'Adres',
    addressPlaceholder: 'Adres kinderdagverblijf',
    create: 'Aanmaken',
    joinNurseryTitle: 'Kinderdagverblijf aansluiten',
    joinNurserySubtitle: 'Voer de code in die de directrice heeft gegeven',
    invitationCode: 'Uitnodigingscode',
    join: 'Aansluiten',
    director: 'Directrice',
    nurseryWorker: 'Kinderverzorgster',
    reportsToWrite: 'Te schrijven rapporten',
    seeAll: 'Alles zien →',
    reportCalendar: 'Rapportkalender',
    allReports: 'Alle rapporten geschreven',
    partialReports: 'Gedeeltelijke rapporten',
    noChildren: 'Nog geen kinderen',
    addChild: '+ Toevoegen',
    addChildTitle: 'Kind toevoegen',
    childCode: 'Kindcode',
    dailyReport: 'Dagelijks rapport',
    lunchMeal: '🍽️ Middageten',
    afternoonMeal: '🍎 Middagsnack',
    nap: '😴 Dutje',
    mood: '😊 Stemming',
    healthNotes: '🏥 Gezondheidsnotities',
    generalNotes: '📝 Algemene notities',
    privateJournal: '📓 Privédagboek',
    privateJournalNote: 'Alleen zichtbaar voor kinderverzorgsters',
    saveDraft: '💾 Concept opslaan',
    publishReport: '✓ Rapport publiceren',
    draftSaved: 'Concept opgeslagen',
    reportPublished: 'Rapport gepubliceerd!',
    draftNotVisible: 'Nog niet zichtbaar voor ouders.',
    parentsCanSee: 'Ouders kunnen het nu bekijken.',
    noMessages: 'Geen berichten',
    writeReply: 'Schrijf een antwoord...',
    menuOfDay: '🍽️ Menu van de dag',
    addMenu: 'Tik om het menu van vandaag toe te voegen',
    saveMenu: 'Opslaan',
    menuSaved: 'Menu opgeslagen!',
    settingsTitle: 'Instellingen',
    invitationCodes: '🔑 Uitnodigingscodes',
    staffCode: 'Personeelscode (kinderverzorgsters)',
    parentCode: 'Oudercode',
    renewCodes: '🔄 Codes vernieuwen',
    manageMembers: '👥 Leden beheren',
    lightMode: '☀️ Overschakelen naar lichte modus',
    darkMode: '🌙 Overschakelen naar donkere modus',
    deleteAccount: 'Account verwijderen',
    logout: '→ Uitloggen',
    language: '🌍 Taal',
    noChildLinked: 'Geen kind gekoppeld',
    addChildWithCode: 'Voeg uw kinderen toe met de code van het kinderdagverblijf',
    addChildArrow: 'Kind toevoegen →',
    sendMessage: 'Bericht sturen',
    sendMessageSubtitle: 'Informeer het team over belangrijke informatie',
    todayReport: 'Rapport van vandaag',
    noReportToday: 'Nog geen rapport vandaag',
    history: 'Geschiedenis',
    photosTitle: "Foto's",
    addPhoto: '+ Foto',
    takePhoto: '📷 Foto nemen',
    choosePhoto: "🖼️ Kiezen uit galerij",
    setAvatar: 'Avatar',
    noPhotos: "Geen foto's",
    membersTitle: 'Leden',
    parent: 'Ouder',
    cancel: 'Annuleren',
    delete: 'Verwijderen',
    confirm: 'Bevestigen',
    error: 'Fout',
    success: 'Succes',
    loading: 'Laden...',
    back: '← Terug',
    add: 'Toevoegen',
    save: 'Opslaan',
    send: 'Versturen',
    present: 'Aanwezig',
    absent: 'Afwezig',
    petiteSection: 'Babygroep',
    grandeSection: 'Peutergroep',
    searchChild: 'Zoek een kind...',
    addMeal: '+ Maaltijd toevoegen',
    addNap: '+ Dutje toevoegen',
    babyReport: 'Babyrapport',
    bigReport: 'Peuterrapport',
    bottle: 'Fles',
    puree: 'Puree',
    compote: 'Compote',
    snack: 'Snack',
    quantity: 'Hoeveelheid (ml)',
    time: 'Tijd',
    duration: 'Duur (min)',
    startTime: 'Begin',
    endTime: 'Einde',
  }
};

export const ThemeContext = createContext({
  isDark: false,
  toggleTheme: () => {},
  theme: colors.light,
  language: 'fr',
  setLanguage: () => {},
  t: (key) => key,
});

export function useTheme() {
  return useContext(ThemeContext);
}