import { createContext, useContext } from 'react';

export const colors = {
  light: {
    background: '#f8f7ff',
    card: '#ffffff',
    text: '#1a1a2e',
    textSecondary: '#6b7280',
    border: '#e5e7eb',
    primary: '#7c3aed',
    primaryLight: '#ede9fe',
    inputBg: '#ffffff',
    inputBorder: '#e5e7eb',
    navBg: '#ffffff',
    navBorder: '#e5e7eb',
    placeholder: '#9ca3af',
    danger: '#ef4444',
    success: '#10b981',
    warning: '#f59e0b',
    cardStat1: '#ede9fe',
    cardStat2: '#d1fae5',
    cardStat3: '#fef3c7',
    cardStat4: '#fce7f3',
  },
  dark: {
    background: '#0a0a0a',
    card: '#1a1a1a',
    text: '#ffffff',
    textSecondary: '#9ca3af',
    border: '#2a2a2a',
    primary: '#7c3aed',
    primaryLight: '#2e1065',
    inputBg: '#1a1a1a',
    inputBorder: '#2a2a2a',
    navBg: '#111111',
    navBorder: '#2a2a2a',
    placeholder: '#6b7280',
    danger: '#ef4444',
    success: '#10b981',
    warning: '#f59e0b',
    cardStat1: '#1e1b4b',
    cardStat2: '#064e3b',
    cardStat3: '#451a03',
    cardStat4: '#4a044e',
  }
};

export const translations = {
  fr: {
    home: 'Accueil',
    children: 'Enfants',
    photos: 'Photos',
    messages: 'Messages',
    agenda: 'Agenda',
    settings: 'Réglages',
    myChildren: 'Mes enfants',
    welcomeBack: 'Bienvenue',
    loginSubtitle: 'Connectez-vous à votre compte',
    email: 'Email',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié ?',
    login: 'Se connecter',
    noAccount: 'Pas encore de compte ?',
    createOne: 'Créer un compte',
    createAccount: 'Créer un compte',
    joinApp: 'Rejoignez Baby-link',
    firstName: 'Prénom',
    lastName: 'Nom',
    welcomeTo: 'Bienvenue sur\nBaby-link',
    onboardingSubtitle: 'Commencez par créer ou rejoindre une crèche',
    createNursery: 'Créer une crèche',
    joinNursery: 'Rejoindre une crèche',
    createNurseryTitle: 'Créer une crèche',
    createNurserySubtitle: 'Vous serez la directrice de cette crèche',
    nurseryName: 'Nom de la crèche',
    nurseryNamePlaceholder: 'Ex: Les Petits Anges',
    address: 'Adresse',
    addressPlaceholder: 'Adresse de la crèche',
    create: 'Créer la crèche',
    joinNurseryTitle: 'Rejoindre une crèche',
    joinNurserySubtitle: 'Entrez le code fourni par la directrice',
    invitationCode: 'Code d\'invitation',
    join: 'Rejoindre',
    director: 'Directrice',
    nurseryWorker: 'Puéricultrice',
    reportsToWrite: 'Rapports à rédiger',
    seeAll: 'Tout voir →',
    reportCalendar: 'Calendrier des rapports',
    allReports: 'Tous les rapports écrits',
    partialReports: 'Rapports partiels',
    noChildren: 'Aucun enfant pour le moment',
    addChild: '+ Ajouter',
    addChildTitle: 'Ajouter un enfant',
    childCode: 'Code enfant',
    dailyReport: 'Rapport du jour',
    lunchMeal: '🍽️ Repas midi',
    afternoonMeal: '🍎 Repas après-midi',
    nap: '😴 Sieste',
    mood: '😊 Humeur',
    healthNotes: '🏥 Notes santé',
    generalNotes: '📝 Notes générales',
    saveDraft: '💾 Enregistrer brouillon',
    publishReport: '✓ Publier le rapport',
    draftSaved: 'Brouillon enregistré',
    reportPublished: 'Rapport publié !',
    draftNotVisible: 'Non visible par les parents pour l\'instant.',
    parentsCanSee: 'Les parents peuvent maintenant le consulter.',
    noMessages: 'Aucun message',
    writeReply: 'Écrire une réponse...',
    menuOfDay: '🍽️ Menu du jour',
    addMenu: 'Appuyez pour ajouter le menu du jour',
    saveMenu: 'Sauvegarder',
    menuSaved: 'Menu sauvegardé !',
    settingsTitle: 'Réglages',
    invitationCodes: '🔑 Codes d\'invitation',
    staffCode: 'Code personnel (puéricultrices)',
    parentCode: 'Code parents',
    renewCodes: '🔄 Renouveler les codes',
    manageMembers: '👥 Gérer les membres',
    lightMode: '☀️ Passer en mode clair',
    darkMode: '🌙 Passer en mode sombre',
    deleteAccount: 'Supprimer le compte',
    logout: '→ Déconnexion',
    language: '🌍 Langue',
    noChildLinked: 'Aucun enfant lié',
    addChildWithCode: 'Ajoutez vos enfants avec le code fourni par la crèche',
    addChildArrow: 'Ajouter un enfant →',
    sendMessage: 'Envoyer un message',
    sendMessageSubtitle: 'Prévenez l\'équipe d\'une info importante',
    todayReport: '📋 Rapport d\'aujourd\'hui',
    noReportToday: 'Pas encore de rapport aujourd\'hui',
    history: '📚 Historique',
    photosTitle: 'Photos',
    addPhoto: '+ Photo',
    takePhoto: '📷 Prendre une photo',
    choosePhoto: '🖼️ Choisir dans la galerie',
    setAvatar: 'Avatar',
    noPhotos: 'Aucune photo',
    membersTitle: 'Membres',
    parent: 'Parent',
    cancel: 'Annuler',
    delete: 'Supprimer',
    confirm: 'Confirmer',
    error: 'Erreur',
    success: 'Succès',
    loading: 'Chargement...',
    back: '← Retour',
    add: 'Ajouter',
    save: 'Sauvegarder',
    send: 'Envoyer',
  },
  en: {
    home: 'Home',
    children: 'Children',
    photos: 'Photos',
    messages: 'Messages',
    agenda: 'Agenda',
    settings: 'Settings',
    myChildren: 'My children',
    welcomeBack: 'Welcome',
    loginSubtitle: 'Log in to your account',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    login: 'Log in',
    noAccount: 'Don\'t have an account?',
    createOne: 'Create one',
    createAccount: 'Create account',
    joinApp: 'Join Baby-link',
    firstName: 'First name',
    lastName: 'Last name',
    welcomeTo: 'Welcome to\nBaby-link',
    onboardingSubtitle: 'Start by creating or joining a nursery',
    createNursery: 'Create a nursery',
    joinNursery: 'Join a nursery',
    createNurseryTitle: 'Create a nursery',
    createNurserySubtitle: 'You will be the director of this nursery',
    nurseryName: 'Nursery name',
    nurseryNamePlaceholder: 'Ex: The Little Angels',
    address: 'Address',
    addressPlaceholder: 'Nursery address',
    create: 'Create nursery',
    joinNurseryTitle: 'Join a nursery',
    joinNurserySubtitle: 'Enter the code provided by the director',
    invitationCode: 'Invitation code',
    join: 'Join',
    director: 'Director',
    nurseryWorker: 'Nursery worker',
    reportsToWrite: 'Reports to write',
    seeAll: 'See all →',
    reportCalendar: 'Report calendar',
    allReports: 'All reports written',
    partialReports: 'Partial reports',
    noChildren: 'No children yet',
    addChild: '+ Add',
    addChildTitle: 'Add a child',
    childCode: 'Child code',
    dailyReport: 'Daily report',
    lunchMeal: '🍽️ Lunch',
    afternoonMeal: '🍎 Afternoon snack',
    nap: '😴 Nap',
    mood: '😊 Mood',
    healthNotes: '🏥 Health notes',
    generalNotes: '📝 General notes',
    saveDraft: '💾 Save draft',
    publishReport: '✓ Publish report',
    draftSaved: 'Draft saved',
    reportPublished: 'Report published!',
    draftNotVisible: 'Not visible to parents yet.',
    parentsCanSee: 'Parents can now view it.',
    noMessages: 'No messages',
    writeReply: 'Write a reply...',
    menuOfDay: '🍽️ Menu of the day',
    addMenu: 'Tap to add today\'s menu',
    saveMenu: 'Save',
    menuSaved: 'Menu saved!',
    settingsTitle: 'Settings',
    invitationCodes: '🔑 Invitation codes',
    staffCode: 'Staff code (nursery workers)',
    parentCode: 'Parent code',
    renewCodes: '🔄 Renew codes',
    manageMembers: '👥 Manage members',
    lightMode: '☀️ Switch to light mode',
    darkMode: '🌙 Switch to dark mode',
    deleteAccount: 'Delete account',
    logout: '→ Log out',
    language: '🌍 Language',
    noChildLinked: 'No child linked',
    addChildWithCode: 'Add your children with the code provided by the nursery',
    addChildArrow: 'Add a child →',
    sendMessage: 'Send a message',
    sendMessageSubtitle: 'Notify the team of important information',
    todayReport: '📋 Today\'s report',
    noReportToday: 'No report yet today',
    history: '📚 History',
    photosTitle: 'Photos',
    addPhoto: '+ Photo',
    takePhoto: '📷 Take a photo',
    choosePhoto: '🖼️ Choose from gallery',
    setAvatar: 'Avatar',
    noPhotos: 'No photos',
    membersTitle: 'Members',
    parent: 'Parent',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    error: 'Error',
    success: 'Success',
    loading: 'Loading...',
    back: '← Back',
    add: 'Add',
    save: 'Save',
    send: 'Send',
  },
  nl: {
    home: 'Thuis',
    children: 'Kinderen',
    photos: 'Foto\'s',
    messages: 'Berichten',
    agenda: 'Agenda',
    settings: 'Instellingen',
    myChildren: 'Mijn kinderen',
    welcomeBack: 'Welkom',
    loginSubtitle: 'Log in op uw account',
    email: 'E-mail',
    password: 'Wachtwoord',
    forgotPassword: 'Wachtwoord vergeten?',
    login: 'Inloggen',
    noAccount: 'Nog geen account?',
    createOne: 'Maak er een',
    createAccount: 'Account aanmaken',
    joinApp: 'Word lid van Baby-link',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    welcomeTo: 'Welkom bij\nBaby-link',
    onboardingSubtitle: 'Begin met het aanmaken of aansluiten bij een kinderdagverblijf',
    createNursery: 'Kinderdagverblijf aanmaken',
    joinNursery: 'Kinderdagverblijf aansluiten',
    createNurseryTitle: 'Kinderdagverblijf aanmaken',
    createNurserySubtitle: 'U wordt de directrice van dit kinderdagverblijf',
    nurseryName: 'Naam kinderdagverblijf',
    nurseryNamePlaceholder: 'Bijv: De Kleine Engeltjes',
    address: 'Adres',
    addressPlaceholder: 'Adres kinderdagverblijf',
    create: 'Aanmaken',
    joinNurseryTitle: 'Kinderdagverblijf aansluiten',
    joinNurserySubtitle: 'Voer de code in die de directrice heeft gegeven',
    invitationCode: 'Uitnodigingscode',
    join: 'Aansluiten',
    director: 'Directrice',
    nurseryWorker: 'Kinderverzorgster',
    reportsToWrite: 'Te schrijven rapporten',
    seeAll: 'Alles zien →',
    reportCalendar: 'Rapportkalender',
    allReports: 'Alle rapporten geschreven',
    partialReports: 'Gedeeltelijke rapporten',
    noChildren: 'Nog geen kinderen',
    addChild: '+ Toevoegen',
    addChildTitle: 'Kind toevoegen',
    childCode: 'Kindcode',
    dailyReport: 'Dagelijks rapport',
    lunchMeal: '🍽️ Middageten',
    afternoonMeal: '🍎 Middagsnack',
    nap: '😴 Dutje',
    mood: '😊 Stemming',
    healthNotes: '🏥 Gezondheidsnotities',
    generalNotes: '📝 Algemene notities',
    saveDraft: '💾 Concept opslaan',
    publishReport: '✓ Rapport publiceren',
    draftSaved: 'Concept opgeslagen',
    reportPublished: 'Rapport gepubliceerd!',
    draftNotVisible: 'Nog niet zichtbaar voor ouders.',
    parentsCanSee: 'Ouders kunnen het nu bekijken.',
    noMessages: 'Geen berichten',
    writeReply: 'Schrijf een antwoord...',
    menuOfDay: '🍽️ Menu van de dag',
    addMenu: 'Tik om het menu van vandaag toe te voegen',
    saveMenu: 'Opslaan',
    menuSaved: 'Menu opgeslagen!',
    settingsTitle: 'Instellingen',
    invitationCodes: '🔑 Uitnodigingscodes',
    staffCode: 'Personeelscode (kinderverzorgsters)',
    parentCode: 'Oudercode',
    renewCodes: '🔄 Codes vernieuwen',
    manageMembers: '👥 Leden beheren',
    lightMode: '☀️ Overschakelen naar lichte modus',
    darkMode: '🌙 Overschakelen naar donkere modus',
    deleteAccount: 'Account verwijderen',
    logout: '→ Uitloggen',
    language: '🌍 Taal',
    noChildLinked: 'Geen kind gekoppeld',
    addChildWithCode: 'Voeg uw kinderen toe met de code van het kinderdagverblijf',
    addChildArrow: 'Kind toevoegen →',
    sendMessage: 'Bericht sturen',
    sendMessageSubtitle: 'Informeer het team over belangrijke informatie',
    todayReport: '📋 Rapport van vandaag',
    noReportToday: 'Nog geen rapport vandaag',
    history: '📚 Geschiedenis',
    photosTitle: 'Foto\'s',
    addPhoto: '+ Foto',
    takePhoto: '📷 Foto nemen',
    choosePhoto: '🖼️ Kiezen uit galerij',
    setAvatar: 'Avatar',
    noPhotos: 'Geen foto\'s',
    membersTitle: 'Leden',
    parent: 'Ouder',
    cancel: 'Annuleren',
    delete: 'Verwijderen',
    confirm: 'Bevestigen',
    error: 'Fout',
    success: 'Succes',
    loading: 'Laden...',
    back: '← Terug',
    add: 'Toevoegen',
    save: 'Opslaan',
    send: 'Versturen',
  }
};

export const ThemeContext = createContext({
  isDark: true,
  toggleTheme: () => {},
  theme: colors.dark,
  language: 'fr',
  setLanguage: () => {},
  t: (key) => key,
});

export function useTheme() {
  return useContext(ThemeContext);
}